[theme]
base = "light"
primaryColor = "#FFC107"               # Amber/Yellow (Highlight)
backgroundColor = "#ffffff"            # White
secondaryBackgroundColor = "#f4f9f4"   # Mint White
textColor = "#2c3e50"                  # Dark Gray-Blue
font = "sans serif"
